# -*- coding: utf-8 -*-
"""Merge curated online skills with hand-written zh-TW overviews -> web/data/skills.js"""
import json, os, sys, hashlib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CUR = os.path.join(HERE, "curated_raw.json")
OUT = os.path.join(ROOT, "web", "data", "skills.js")

TAGS = {
    "ai-ml": "AI / 機器學習", "typescript": "TypeScript / JS", "python": "Python",
    "java": "Java", "dotnet": ".NET / C#", "rust": "Rust",
    "frontend": "前端", "backend": "後端", "database": "資料庫", "auth": "身分驗證",
    "payments": "金流支付", "devops": "DevOps / 部署", "cloud": "雲端服務",
    "gpu": "GPU / 高效能運算", "mobile": "行動開發", "testing": "測試", "security": "資安",
    "data": "資料處理", "docs": "文件 / 寫作", "automation": "自動化 / 通知",
    "observability": "可觀測性 / 監控", "search": "搜尋 / 爬取", "web3": "Web3 / 加密貨幣",
    "design": "設計 / 視覺", "marketing": "行銷", "product": "產品管理",
    "notion": "Notion / 知識管理", "misc": "其他 / 工具",
}

# name -> 繁體中文概述
OV = {
"anthropics/docx": "建立、編輯與分析 Word 文件。",
"anthropics/doc-coauthoring": "協作式文件編輯與共同撰寫。",
"anthropics/pptx": "建立、編輯與分析 PowerPoint 簡報。",
"voltagent/create-voltagent": "VoltAgent 專案建置指南，含 CLI 與手動步驟。",
"voltagent/voltagent-best-practices": "VoltAgent 的代理、工作流、記憶與伺服器架構與用法模式。",
"voltagent/voltagent-core-reference": "VoltAgent 類別選項與生命週期方法參考。",
"angular/angular-developer": "產生 Angular 程式碼，提供元件、服務與反應式架構指引。",
"angular/angular-new-app": "用 CLI 以現代最佳實踐建立新的 Angular 專案。",
"composiohq/composio": "讓 AI 代理透過託管驗證連接 1000+ 外部應用。",
"supabase/postgres-best-practices": "Supabase 上的 PostgreSQL 最佳實踐。",
"google-gemini/gemini-api-dev": "用 Gemini API 開發 Gemini 應用的最佳實踐。",
"google-gemini/vertex-ai-api-dev": "在 Google Cloud Vertex AI 上用 Gen AI SDK 開發 Gemini 應用。",
"google-gemini/gemini-live-api-dev": "用 Gemini Live API 建構即時雙向串流應用。",
"stripe/stripe-best-practices": "建構 Stripe 整合的最佳實踐。",
"stripe/upgrade-stripe": "升級 Stripe SDK 與 API 版本。",
"trycourier/courier-skills": "透過 email、簡訊、推播與聊天的多通道通知。",
"callstackincubator/react-native-best-practices": "React Native 應用的效能優化（Callstack）。",
"callstackincubator/github": "PR、程式碼審查與分支的 GitHub 工作流模式。",
"callstackincubator/upgrading-react-native": "React Native 升級流程：範本、相依套件與常見陷阱。",
"better-auth/best-practices": "Better Auth 整合最佳實踐。",
"better-auth/explain-error": "解釋 Better Auth 的錯誤訊息。",
"better-auth/providers": "Better Auth 的各種驗證提供者。",
"tinybirdco/tinybird-best-practices": "Tinybird 的 datasource、pipe、endpoint 與 SQL 專案指南。",
"tinybirdco/tinybird-cli-guidelines": "Tinybird CLI 使用指南與指令。",
"tinybirdco/tinybird-python-sdk-guidelines": "Tinybird Python SDK 使用指南。",
"hashicorp/azure-verified-modules": "Terraform 模組的 Azure Verified Modules (AVM) 認證標準。",
"hashicorp/new-terraform-provider": "用 Plugin Framework 建立新的 Terraform provider 專案骨架。",
"hashicorp/provider-resources": "用 Plugin Framework 實作 Terraform provider 的 resource 與 data source。",
"sanity-io/sanity-best-practices": "Sanity Studio、GROQ 查詢與內容工作流最佳實踐。",
"sanity-io/content-modeling-best-practices": "在 Sanity 設計可擴展內容模型的指南。",
"sanity-io/seo-aeo-best-practices": "內容網站的 SEO 與答案引擎優化（AEO）模式。",
"firecrawl/firecrawl-build": "把 Firecrawl 整合進程式碼，做網頁搜尋、爬取、擷取與瀏覽器互動。",
"firecrawl/firecrawl-build-interact": "多步驟 Firecrawl 瀏覽器流程：點擊、填表、分頁與帶驗證的導覽。",
"firecrawl/firecrawl-build-onboarding": "首次整合：在專案設定 Firecrawl 憑證與 SDK。",
"neondatabase/neon-postgres": "Neon Serverless Postgres 最佳實踐。",
"neondatabase/claimable-postgres": "用 Neon 佈建可認領（claimable）的 Postgres 資料庫。",
"neondatabase/neon-postgres-egress-optimizer": "優化 Neon Postgres 的流出流量與資料傳輸。",
"clickhouse/clickhouse-best-practices": "使用 ClickHouse 的最佳實踐。",
"clickhouse/chdb-datastore": "可直接取代 pandas、跨 16+ 資料來源具 ClickHouse 效能的資料層。",
"clickhouse/chdb-sql": "行程內 ClickHouse SQL 引擎，免伺服器即可查詢檔案、資料庫與雲端儲存。",
"remotion-dev/remotion": "用 React 以程式化方式製作影片。",
"replicate/replicate": "透過 Replicate API 探索、比較與執行 AI 模型。",
"typefully/typefully": "跨 X、LinkedIn、Threads、Bluesky、Mastodon 建立、排程與發布社群貼文。",
"veniceai/venice-api-overview": "Venice API 基礎：驗證模式、定價與版本。",
"veniceai/venice-auth": "Venice 的 API 金鑰與錢包式驗證。",
"veniceai/venice-chat": "Venice 的聊天補全、多模態輸入、工具與串流。",
"vercel-labs/next-best-practices": "Next.js 最佳實踐與建議模式。",
"vercel-labs/next-cache-components": "Next.js 的快取策略與快取感知元件。",
"vercel-labs/next-upgrade": "將 Next.js 專案升級到新版本。",
"cloudflare/agents-sdk": "用排程、RPC 與 MCP 伺服器建構具狀態的 AI 代理。",
"cloudflare/cloudflare": "涵蓋 Workers、Pages、儲存、AI、網路、資安與 IaC 的完整 Cloudflare 平台技能。",
"cloudflare/cloudflare-email-service": "用 Cloudflare Email 收發交易郵件與路由進站郵件。",
"netlify/netlify-functions": "建構無伺服器 API 端點與背景任務。",
"netlify/netlify-edge-functions": "低延遲的邊緣中介層與地理定位邏輯。",
"netlify/netlify-blobs": "用於檔案與資料的鍵值物件儲存。",
"google-labs-code/design-md": "建立與管理 DESIGN.md 設計文件。",
"google-labs-code/enhance-prompt": "用設計規格與 UI/UX 詞彙改善提示詞。",
"google-labs-code/react-components": "把 Stitch 設計轉成 React 元件。",
"googleworkspace/gws-shared": "Google Workspace CLI 的共用驗證、全域旗標與輸出格式。",
"googleworkspace/gws-drive": "管理 Google Drive 檔案、資料夾與共用雲端硬碟。",
"googleworkspace/gws-sheets": "讀寫 Google Sheets 試算表。",
"expo/building-native-ui": "用 Expo Router、樣式、元件、導覽與動畫建構原生 App UI。",
"expo/expo-api-routes": "在 Expo Router 用 EAS Hosting 建立 API route。",
"expo/expo-cicd-workflows": "Expo 專案的 CI/CD 工作流。",
"huggingface/hf-cli": "操作 Hugging Face Hub 的 HF CLI 工具。",
"huggingface/hugging-face-dataset-viewer": "用 Dataset Viewer API 瀏覽與查詢 HF 資料集。",
"huggingface/hugging-face-datasets": "建立與管理含設定與 SQL 查詢的 HF 資料集。",
"trailofbits/ask-questions-if-underspecified": "當需求模糊時主動提問釐清。",
"getsentry/sentry-sdk-setup": "在任何語言/框架設定 Sentry，自動偵測平台並導向正確 SDK。",
"getsentry/sentry-workflow": "端到端 Sentry 工作流：以 Sentry 脈絡修正線上問題與審查程式碼。",
"getsentry/sentry-fix-issues": "透過 MCP 以堆疊追蹤、breadcrumb 與 trace 脈絡找出並修正 Sentry 問題。",
"microsoft/cloud-solution-architect": "設計架構良好的 Azure 雲端系統。",
"microsoft/continual-learning": "Azure AI 的持續學習模式。",
"microsoft/copilot-sdk": "用 GitHub Copilot SDK 打造應用。",
"microsoft/azure-ai-document-intelligence-dotnet": "文件文字、表格與資料擷取（.NET）。",
"microsoft/azure-ai-anomalydetector-java": "異常偵測應用（Java）。",
"microsoft/agent-framework-azure-ai-py": "Azure AI Foundry 的 Agent Framework（Python）。",
"microsoft/azure-cosmos-rust": "Cosmos DB NoSQL 用戶端（Rust）。",
"microsoft/azure-ai-contentsafety-ts": "文字與圖片的內容安全（TypeScript）。",
"fal-ai-community/fal-3d": "從文字或圖片生成 3D 模型。",
"fal-ai-community/fal-audio": "用 fal.ai 音訊模型做文字轉語音與語音轉文字。",
"fal-ai-community/fal-generate": "用 fal.ai 模型生成圖片與影片。",
"WordPress/wordpress-router": "分類 WordPress 儲存庫並導向正確工作流。",
"WordPress/wp-project-triage": "自動偵測專案類型、工具鏈與版本。",
"WordPress/wp-block-development": "Gutenberg 區塊開發：block.json、屬性、渲染與棄用處理。",
"openai/cloudflare-deploy": "用 Workers、Pages 等服務把應用部署到 Cloudflare。",
"openai/develop-web-game": "用 Playwright 以時間步進方式反覆建構與測試網頁遊戲。",
"openai/doc": "讀取、建立與編輯 .docx，保留格式與版面。",
"figma/figma-code-connect-components": "用 Code Connect 把 Figma 設計元件連到程式元件。",
"figma/figma-create-design-system-rules": "為 Figma-to-code 工作流產生專案專屬的設計系統規則。",
"figma/figma-create-new-file": "建立新的空白 Figma Design 或 FigJam 檔。",
"coreyhaines31/ab-test-setup": "為任何數位體驗規劃與實作 A/B 測試或實驗。",
"realkimbarrett/avatar-extraction": "精確定義買家是誰、想要什麼、試過什麼，以及決策驅動因素。",
"binance/crypto-market-rank": "查詢加密貨幣市場排名：熱門代幣、聰明錢流入、迷因排行與頂級交易者盈虧榜。",
"binance/meme-rush": "追蹤 launchpad（Pump.fun、Four.meme）即時迷因代幣與 AI 熱門市場主題（依淨流入排序）。",
"binance/query-address-info": "查詢 BSC、Base 或 Solana 上任一錢包地址的代幣持倉與投組。",
"apollographql/apollo-client": "用 Apollo Client 4 建構 React 應用。",
"apollographql/apollo-connectors": "用 Apollo Connectors 把 REST API 整合進 GraphQL supergraph。",
"apollographql/apollo-federation": "撰寫 Apollo Federation 2 subgraph schema 並組成 supergraph。",
"auth0/auth0-android": "用 Auth0 SDK 為原生 Android App 加入驗證。",
"auth0/auth0-angular": "用 @auth0/auth0-angular 為 Angular App 加入驗證。",
"auth0/auth0-aspnetcore-api": "為 ASP.NET Core API 加入 JWT 存取權杖驗證。",
"brave/answers": "以即時網路搜尋結果為依據生成 AI 答案。",
"brave/bx": "專為 AI 代理打造的網頁搜尋 CLI 工具。",
"brave/images-search": "用 Brave Search API 搜尋圖片。",
"browserbase/browser": "用自然語言 CLI 指令自動化網頁瀏覽器操作。",
"browserbase/browserbase-cli": "Browserbase 平台的 CLI 包裝工具。",
"browserbase/cookie-sync": "把本機 Chrome 的 cookie 匯出到 Browserbase 持久情境。",
"coderabbitai/autofix": "抓取 GitHub PR 上未解決的 CodeRabbit 審查意見並套用修正。",
"coderabbitai/code-review": "透過 CodeRabbit CLI 執行 AI 程式碼審查。",
"coinbase/authenticate-wallet": "用 email OTP 處理 Coinbase 付款錢包登入。",
"coinbase/fund": "透過 Coinbase Onramp 為錢包加值 USDC。",
"coinbase/monetize-service": "用 x402 建立按次收取 USDC 的 Express 伺服器。",
"datadog-labs/dd-apm": "直接在編輯器查詢 Datadog APM 資料。",
"datadog-labs/dd-docs": "透過 LLM 優化的文件索引查詢 Datadog 文件。",
"datadog-labs/dd-llmo-eval-bootstrap": "分析線上 LLM trace 並產生評估器。",
"firebase/developing-genkit-dart": "用 Genkit Dart SDK 建構 AI 應用。",
"firebase/developing-genkit-go": "用 Genkit Go SDK 建構 AI 應用。",
"firebase/developing-genkit-js": "在 Node.js 用 Firebase Genkit 建構 AI 應用。",
"flutter/flutter-adding-home-screen-widgets": "為 Flutter App 在 Android/iOS 加入主畫面小工具。",
"flutter/flutter-animating-apps": "實作動畫效果、轉場與動態。",
"flutter/flutter-architecting-apps": "用分層架構組織 Flutter App。",
"deanpeters/acquisition-channel-advisor": "用單位經濟評估獲客通道，建議擴大/測試/淘汰。",
"phuryn/ab-test-analysis": "以統計顯著性分析 A/B 測試結果並提供建議。",
"MiniMax-AI/cli": "用 MiniMax AI 生成文字、圖片、影片、語音與音樂。",
"MiniMax-AI/frontend-dev": "全端前端：電影級動畫、MiniMax API 生成媒體與生成式藝術。",
"MiniMax-AI/fullstack-dev": "後端架構：REST API 設計、驗證流程、即時功能與資料庫整合。",
"duckdb/attach-db": "掛載 DuckDB 資料庫檔做互動查詢，並自動探索 schema。",
"duckdb/query": "用 Friendly SQL 對已掛載資料庫或檔案直接查詢。",
"duckdb/read-file": "讀取任意資料檔（CSV、JSON、Parquet、Avro、Excel、空間）本機或遠端。",
"greensock/gsap-core": "GSAP 核心 API：to()、from()、fromTo()、easing、duration、stagger 與預設值。",
"greensock/gsap-timeline": "GSAP 時間軸：序列、位置參數、標籤、巢狀與播放控制。",
"greensock/gsap-scrolltrigger": "ScrollTrigger 捲動連動動畫、pin、scrub 與 refresh 處理。",
"garrytan/office-hours": "YC Office Hours：六個在寫程式前重新框定產品的逼問問題。",
"garrytan/plan-ceo-review": "CEO/創辦人計畫審查四模式：擴張、選擇性擴張、維持範圍、縮減。",
"garrytan/plan-eng-review": "工程主管審查：鎖定架構、資料流、圖表、邊界情況與測試。",
"makenotion/knowledge-capture": "把對話轉成結構化、妥善組織與連結的 Notion 文件頁。",
"makenotion/meeting-intelligence": "蒐集 Notion 脈絡並準備會議預讀資料與議程。",
"makenotion/research-documentation": "搜尋 Notion 工作區、彙整發現並產生完整研究報告。",
"resend/resend": "透過 Resend API 寄送與管理郵件。",
"resend/react-email": "用 React Email 元件設計郵件。",
"resend/email-best-practices": "郵件送達率與設計的最佳實踐。",
"addyosmani/web-quality-audit": "涵蓋效能、無障礙、SEO 與最佳實踐的全面品質審查。",
"addyosmani/performance": "載入速度、執行效率與資源優化。",
"addyosmani/core-web-vitals": "針對 LCP、INP、CLS 的優化。",
"mongodb/mongodb-mcp-setup": "設定 MongoDB MCP 伺服器的驗證與連線。",
"mongodb/mongodb-connection": "優化 MongoDB 連線池、逾時與無伺服器模式。",
"mongodb/mongodb-schema-design": "設計含驗證與索引模式的高效文件 schema。",
"redis/redis-development": "Redis 開發最佳實踐：資料結構、查詢引擎、向量搜尋、快取與效能優化。",
"NVIDIA/CUDA-Q/cudaq-guide": "CUDA-Q 上手指南：安裝、測試程式、GPU 模擬、QPU 硬體與量子應用。",
"NVIDIA/DALI/dali-dynamic-mode": "撰寫 DALI 資料載入/前處理，或轉換為 dynamic 模式時使用。",
"NVIDIA/Megatron-Bridge/adding-model-support": "在 Megatron-Bridge 加入新 LLM/VLM 模型支援的指南。",
"NVIDIA/Megatron-Core/build-and-dependency": "Megatron-LM 的容器化開發環境與相依管理。",
"NVIDIA/Model-Optimizer/accessing-mlflow": "查詢與瀏覽存於 MLflow 的評估結果。",
"NVIDIA/NeMo-Evaluator/byob": "用 BYOB 裝飾器框架建立自訂 LLM 評估基準。",
"NVIDIA/NeMo-Evaluator-Launcher/accessing-mlflow": "查詢與瀏覽存於 MLflow 的評估結果。",
"NVIDIA/NeMo-Gym/add-benchmark": "為 NeMo-Gym 新增基準或訓練環境的指南。",
"NVIDIA/NeMo-RL/auto-research": "NeMo-RL 自主研究代理工作流，做假說測試與開放探索。",
"NVIDIA/NemoClaw/nemoclaw-contributor-create-pr": "建立符合 NemoClaw PR 範本的 GitHub PR。",
"NVIDIA/TensorRT-LLM/ad-accuracy-debug": "對照參考分數除錯 AutoDeploy 的準確度回歸。",
"NVIDIA/TileGym/adding-cutile-kernel": "為 TileGym 新增 cuTile GPU kernel 運算子。",
"NVIDIA/cuopt/cuopt-developer": "修改、建置、測試、除錯與貢獻 NVIDIA cuOpt（C++/CUDA、Python、伺服器、CI）。",
"NVIDIA/deepstream/deepstream-dev": "用 Python pyservicemaker API 開發 NVIDIA DeepStream SDK 9.0。",
"NVIDIA/nemotron-voice-agent/nemotron-voice-agent-deploy": "在工作站（x86）、Jetson Thor 或雲端 NIM 部署 Nemotron 語音代理。",
"NVIDIA/rag/rag-blueprint": "NVIDIA RAG Blueprint：部署、設定、除錯與管理。",
"NVIDIA/video-search-and-summarization/alerts": "部署警示設定後，管理與監控 VSS 警示。",
"google/cloud/agent-platform-skill-registry": "操作 Gemini Enterprise Agent Platform 技能登錄：建立與搜尋技能。",
"google/cloud/alloydb-basics": "管理 AlloyDB for PostgreSQL 叢集、執行個體與備份，並整合 MCP 工具。",
"google/cloud/bigquery-basics": "管理 BigQuery 資料集、表與作業，整合 BigQuery ML 與 Gemini 分析。",
"redhat/cve-skillpack": "理解 CVE、查產品生命週期、蒐集診斷並以正確嚴重度開支援案（Red Hat）。",
"redhat/sre-skillpack": "跨 RHEL 機隊探查、修補與驗證 CVE，串接 Lightspeed 與 Ansible。",
"redhat/openshift-skillpack": "以對話式工作流佈建、盤點與報告 OpenShift 叢集（Assisted Installer、OCM、ROSA、ARO）。",
"cypress-io/cypress-author": "建立、更新與修正 Cypress E2E 與元件測試。",
"cypress-io/cypress-explain": "解釋 Cypress 測試並回答其使用與行為問題。",
"cypress-io/cypress-docs": "從官方文件搜尋與擷取 Cypress 資訊。",
"qdrant/skills": "Qdrant 向量搜尋技能：擴展、效能、品質、監控、部署與多語言 SDK。",
"BrianRWagner/ai-marketing-skills": "17 個行銷框架：陌生開發、首頁稽核、社群卡片等。",
"PSPDFKit-labs/nutrient-agent-skill": "用 Nutrient DWS API 處理文件：轉檔、擷取、OCR、遮蔽 PII、浮水印、簽章與填表。",
"robzolkos/skill-rails-upgrade": "分析 Rails 應用並提供升級評估。",
"muratcankoylan/context-fundamentals": "理解什麼是 context、為何重要，以及代理系統中 context 的結構。",
"transloadit/skills": "Transloadit 檔案處理技能集（6 個）。",
"czlonkowski/n8n-code-javascript": "在 n8n Code 節點用 JavaScript 與資料存取模式。",
}

def main():
    cur = json.load(open(CUR, encoding="utf-8"))
    skills = []
    missing = []
    for r in cur:
        ov = OV.get(r["name"])
        if not ov:
            missing.append(r["name"])
            ov = ""
        skills.append({
            "id": r["name"],
            "name": r["name"].split("/")[-1],
            "fullName": r["name"],
            "vendor": r["vendor"],
            "official": r.get("official", False),
            "url": r["url"],
            "tags": r["tags"],
            "overview": ov,
            "rawDescription": r["rawDescription"],
        })
    skills.sort(key=lambda s: (not s["official"], s["vendor"].lower(), s["name"].lower()))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    tags_json = json.dumps(TAGS, ensure_ascii=False, indent=1)
    skills_json = json.dumps(skills, ensure_ascii=False, indent=1)
    # content stamp drives IndexedDB re-seeding when data changes
    ver = hashlib.md5((tags_json + skills_json).encode("utf-8")).hexdigest()[:12]
    payload = 'window.DATA_VERSION = "%s";\nwindow.TAGS = %s;\nwindow.SKILLS = %s;\n' % (
        ver, tags_json, skills_json,
    )
    open(OUT, "w", encoding="utf-8").write(payload)
    print("WROTE", len(skills), "skills (v%s) ->" % ver, OUT, file=sys.stderr)
    if missing:
        print("MISSING zh overview (%d):" % len(missing), file=sys.stderr)
        for m in missing:
            print("  -", m, file=sys.stderr)

if __name__ == "__main__":
    main()
